apiVersion: v1
kind: Service
metadata:
  name: django-to-do-svc
spec:
  type: NodePort
  selector:
    app: django-to-do-app
  ports:
  - nodePort: 30080
    protocol: TCP
    port: 8000
    targetPort: 8000